name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dashboard:
    name: Dashboard - type-check, lint, test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/dashboard/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm exec tsc -p tsconfig.json --noEmit

      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
  python_lib:
    name: Python lib - type-check, lint, test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: libs/python-lib
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            libs/python-lib/setup.py
            libs/python-lib/pytest.ini
            libs/python-lib/mypy.ini

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Type check (mypy)
        run: |
          if find src -type f -name '*.py' | grep -q .; then
            mypy --config-file mypy.ini src
          else
            echo "No Python files in src; skipping mypy"
          fi

      - name: Lint (flake8)
        run: |
          if find src tests -type f -name '*.py' 2>/dev/null | grep -q .; then
            flake8 src tests
          else
            echo "No Python files to lint; skipping flake8"
          fi

      - name: Test (pytest)
        run: |
          if [ -d tests ] && find tests -type f -name 'test_*.py' | grep -q .; then
            pytest -q
          else
            echo "No tests found; skipping pytest"
          fi

  go_consumer:
    name: Go kafka-consumer - type-check, lint, test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/kafka-consumer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Download modules
        run: go mod download

      - name: Determine packages
        id: golist
        run: |
          set -e
          if go list ./... >/dev/null 2>&1; then
            echo "skip=false" >> "$GITHUB_OUTPUT"
          else
            echo "No Go packages found; skipping build/vet/test"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Type check (build)
        if: steps.golist.outputs.skip == 'false'
        run: go build ./...

      - name: Lint (vet)
        if: steps.golist.outputs.skip == 'false'
        run: go vet ./...

      - name: Test
        if: steps.golist.outputs.skip == 'false'
        run: go test ./...
